name: Deploy
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
jobs:
  push-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Define VERSION ğŸ“
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Push VERSION tag ğŸ“Œ
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ env.VERSION }}
          message: 'Tagging version ${{ env.VERSION }}'
  deploy-pages:
    needs: push-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install Haxe ğŸ“¥
        run: ./.github/scripts/install_haxe.sh
      - name: Install Haxe libs ğŸ“š
        run: yes | haxelib install doc.hxml
      - name: Build documentation ğŸ”§
        run: haxe doc.hxml
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc
          CLEAN: false
  deploy-package:
    needs: deploy-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Install Haxe ğŸ“¥
        run: ./.github/scripts/install_haxe.sh
      - name: Define VERSION ğŸ“
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
      - name: Set haxelib.json version ğŸ“
        run: sed -i "s/0.0.0/${{ env.VERSION }}/g" haxelib.json
      - name: Zip package ğŸ“¦
        run: zip -9 -r -q diff *
      - name: Deploy ğŸš€
        env:
          HAXELIB_PWD: ${{ secrets.HAXELIB_PWD }}
        run: echo "$HAXELIB_PWD" | haxelib submit diff.zip
