name: Push version tag
on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed
jobs:
  push-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
      - name: Push tag with VERSION file ğŸ“Œ
        env:
          VERSION: ${cat VERSION}
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ env.VERSION }}
          message: 'Tagging version ${{ env.VERSION }}'
